Ignore uninlined_format_args pedantic clippy lint
    error: variables can be used directly in the `format!` string
       --> src/deserializer.rs:626:31
        |
    626 |                     E::custom(format_args!("missing field `{}` in {}", field, kind))
        |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
        = note: `-D clippy::uninlined-format-args` implied by `-D clippy::pedantic`
    help: change this to
        |
    626 -                     E::custom(format_args!("missing field `{}` in {}", field, kind))
    626 +                     E::custom(format_args!("missing field `{field}` in {kind}"))
        |

    error: variables can be used directly in the `format!` string
       --> src/deserializer.rs:697:21
        |
    697 |                     write!(formatter, "unknown field `{}`, there are no fields", field)
        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
    help: change this to
        |
    697 -                     write!(formatter, "unknown field `{}`, there are no fields", field)
    697 +                     write!(formatter, "unknown field `{field}`, there are no fields")
        |

    error: variables can be used directly in the `format!` string
       --> src/deserializer.rs:708:17
        |
    708 |                 write!(formatter, "missing field `{}`", field)
        |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
    help: change this to
        |
    708 -                 write!(formatter, "missing field `{}`", field)
    708 +                 write!(formatter, "missing field `{field}`")
        |

    error: variables can be used directly in the `format!` string
       --> src/deserializer.rs:731:21
        |
    731 |                     write!(formatter, "`{}`", alt)?;
        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
    help: change this to
        |
    731 -                     write!(formatter, "`{}`", alt)?;
    731 +                     write!(formatter, "`{alt}`")?;
        |

    error: variables can be used directly in the `format!` string
      --> src/id.rs:22:9
       |
    22 |         write!(formatter, "Id({})", self)
       |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
       = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
    help: change this to
       |
    22 -         write!(formatter, "Id({})", self)
    22 +         write!(formatter, "Id({self})")
       |