Raise minimum supported compiler to rustc 1.46
Required by the use of Option::zip.

    error[E0658]: use of unstable library feature 'option_zip'
       --> src/loc.rs:551:14
        |
    551 |             .zip(self.expansion_loc.as_ref())
        |              ^^^
        |
        = note: see issue #70086 <https://github.com/rust-lang/rust/issues/70086> for more information

    error[E0658]: use of unstable library feature 'option_zip'
       --> src/loc.rs:529:36
        |
    529 |             spelling_included_from.zip(expansion_included_from).map_or(
        |                                    ^^^
        |
        = note: see issue #70086 <https://github.com/rust-lang/rust/issues/70086> for more information