Raise minimum tested compiler to 1.59
Required for const-initialized thread locals support.

    error[E0658]: use of unstable library feature 'thread_local_const_init'
     --> src/dedup.rs:3:1
      |
    3 | / thread_local! {
    4 | |     static REFCOUNT: Cell<usize> = const { Cell::new(0) };
    5 | | }
      | |_^
      |