Work around stack overflow with LLVM 18
This bisects to https://github.com/rust-lang/rust/pull/120055.

    Running tests/exhaustive.rs (target/release/deps/exhaustive-e2f6c3a78f65e6a2)

    running 1 test

    thread 'test' has overflowed its stack
    fatal runtime error: stack overflow
    error: test failed, to rerun pass `--test exhaustive`

    Caused by:
      process didn't exit successfully: `target/release/deps/exhaustive-e2f6c3a78f65e6a2` (signal: 6, SIGABRT: process abort signal)